[build]
builder = "nixpacks"

[deploy]
startCommand = "daphne -b 0.0.0.0 -p $PORT poker_project.asgi:application"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3