# Generated by Django 4.2.7 on 2025-07-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker_api', '0013_playergame_left_at_playergame_left_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='balance',
        ),
    ]
