# Generated by Django 4.2.7 on 2025-07-29 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poker_api', '0014_remove_player_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BotPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('BASIC', 'Basic'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BASIC', max_length=20)),
                ('play_style', models.CharField(choices=[('TIGHT_PASSIVE', 'Tight Passive'), ('TIGHT_AGGRESSIVE', 'Tight Aggressive'), ('LOOSE_PASSIVE', 'Loose Passive'), ('LOOSE_AGGRESSIVE', 'Loose Aggressive')], default='TIGHT_AGGRESSIVE', max_length=20)),
                ('aggression_factor', models.FloatField(default=0.5)),
                ('bluff_frequency', models.FloatField(default=0.1)),
                ('thinking_time_min', models.FloatField(default=1.0)),
                ('thinking_time_max', models.FloatField(default=3.0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poker_api.player')),
            ],
        ),
    ]
